name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SERVER_PASSPHRASE}}
          script: |
            mkdir -p /home/${{secrets.SSH_USERNAME}}/Chornuy
            cd /home/${{secrets.SSH_USERNAME}}/Chornuy
            git clone https://github.com/ValeriyChornuy/lab-2.git
            echo 'Deployment successful to DigitalOcean'
