name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Unet
        uses: actions/checkout@v3
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
     
          script: |
            mkdir -p /root/Chornuy
            cd /root/Chornuy
            git clone https://github.com/ValeriyChornuy/lab-2.git
            echo 'Deployment successful to DigitalOcean'

