name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Connecting to server..."
            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'rm -rf /home/valerachornuy/htdocs && mkdir -p /home/valerachornuy/htdocs && git clone https://github.com/ValeriyChornuy/lab-2' || (echo "Failed to clone repository"; exit 1)
            echo "Repository cloned successfully"
