name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Unet
        uses: actions/checkout@v3
        with:
          repository: ValeriyChornuy/lab-2
          token: ${{secrets.GITHUB_TOKEN}}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Clone repository
        run: |
          mkdir -p /root/Chornuy
          cd /root/Chornuy
          git clone https://github.com/ValeriyChornuy/lab-2.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Display success message
        run: echo 'Deployment successful to DigitalOcean'
